### ISSUE TITLE
Line number mapping is broken after pull/40

### ISSUE THREAD

**Issue by minhhn2910** [sbip-sg/solc-json-parser#41] opened 2022-12-22 09:27 UTC
After this PR https://github.com/sbip-sg/solc-json-parser/pull/40/ , the line number mapping `source_by_pc` now cant map for the `Test` contract in this sample : 
```
// SPDX-License-Identifier: MIT
pragma solidity 0.7.6;
pragma experimental ABIEncoderV2;

contract Test {
  struct Sig { uint8 v; bytes32 r; bytes32 s;}

  function claim(bytes32 _msg, Sig memory sig) public {
    address signer = ecrecover(_msg, sig.v, sig.r, sig.s);
    // require(signer == owner);
    payable(msg.sender).transfer(address(this).balance);
  }

  function vec_add(uint[2] memory a, uint[2] memory b) public returns (uint[2] memory c){
    c[0] = a[0] + b[0]; //overflow
    c[1] = a[1] + b[1]; //overflow
  }
}
```
Line mapping was ok for the commit right before this. 
```
SOLC_OPTIMIZATION = 200
Call: source_by_pc(Test, 278, False)
sample.sol IntegerOverflow 1 278
15     c[0] = a[0] + b[0]; //overflow
--------------------------------------------------------------------------------
Call: source_by_pc(Test, 293, False)
sample.sol IntegerOverflow 1 293
16     c[1] = a[1] + b[1]; //overflow

```

**Comment by minhhn2910** [comment] 2022-12-22 09:40
This bug is so dangerous because it's vital for other parts of the systems to work. I think we should have better unittest for this part.

**Comment by YoungHS-NUS** [comment] 2022-12-22 10:02
I will take a deeper look.

**Comment by cl2089** [comment] 2022-12-22 13:05
Hi guys I didn't have much time to check this, but I think it's very likely caused by missing the optimization option caused by the update here:

![image](https://user-images.githubusercontent.com/1858231/209140069-3f8a3312-4e65-4b39-bfeb-009545449060.png)

After the update, the `optimize`, `optimze-runs` etc options inside `self.solc_options` are not passed to the solcx compiler.

**Comment by YoungHS-NUS** [comment] 2022-12-22 17:01
After some preliminary testing, my findings are in alignment with CL's idea. 
When merging main to my develop branch, I accidentally missed out `**self.solc_options` when I was solving the merge conflict.
Having the option and setting optimize=True will correct the behavior.
I will write more unittests tomorrow to confirm and also make our test more robust.

**Comment by cl2089** [comment] 2022-12-27 04:19
@minhhn2910 should be fixed by [this PR](https://github.com/sbip-sg/solc-json-parser/commit/cba30be49f6f8c0f85bd7ca098ff6686ef683486#diff-e7d0bb978373d9dc2d537a04d4bd55fb9bf34eb4ac152e98358ebe1352d88b04R549)

**Closed** 2022-12-27 05:20 UTC
